# 1. Usar imagen de Node.js para construir la app
FROM node:18 AS build
WORKDIR /app
COPY . .

COPY package*.json ./
# Ajustar package.json para que apunte a la carpeta dentro de Docker


RUN npm install
RUN npm list --depth=0

COPY . .
RUN npm run build

# 2. Usar Nginx para servir la app
FROM nginx:latest
COPY --from=build /app/dist/redSocial /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
